#include <core/protocol/get_config.hpp>
#include <core/protocol/config.hpp>
#include <core/protocol/asset.hpp>
#include <core/protocol/types.hpp>
#include <core/protocol/version.hpp>

namespace core { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
#else
   result[ "IS_TEST_NET" ] = false;
#endif

   result["SBD_SYMBOL"] = SBD_SYMBOL;
   result["CORE_100_PERCENT"] = CORE_100_PERCENT;
   result["CORE_1_PERCENT"] = CORE_1_PERCENT;
   result["CORE_1_TENTH_PERCENT"] = CORE_1_TENTH_PERCENT;
   result["CORE_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = CORE_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["CORE_ACTIVE_CHALLENGE_COOLDOWN"] = CORE_ACTIVE_CHALLENGE_COOLDOWN;
   result["CORE_ACTIVE_CHALLENGE_FEE"] = CORE_ACTIVE_CHALLENGE_FEE;
   result["CORE_ADDRESS_PREFIX"] = CORE_ADDRESS_PREFIX;
   result["CORE_APR_PERCENT_MULTIPLY_PER_BLOCK"] = CORE_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["CORE_APR_PERCENT_MULTIPLY_PER_HOUR"] = CORE_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["CORE_APR_PERCENT_MULTIPLY_PER_ROUND"] = CORE_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["CORE_APR_PERCENT_SHIFT_PER_BLOCK"] = CORE_APR_PERCENT_SHIFT_PER_BLOCK;
   result["CORE_APR_PERCENT_SHIFT_PER_HOUR"] = CORE_APR_PERCENT_SHIFT_PER_HOUR;
   result["CORE_APR_PERCENT_SHIFT_PER_ROUND"] = CORE_APR_PERCENT_SHIFT_PER_ROUND;
   result["CORE_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = CORE_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["CORE_BANDWIDTH_PRECISION"] = CORE_BANDWIDTH_PRECISION;
   result["CORE_BLOCKCHAIN_PRECISION"] = CORE_BLOCKCHAIN_PRECISION;
   result["CORE_BLOCKCHAIN_PRECISION_DIGITS"] = CORE_BLOCKCHAIN_PRECISION_DIGITS;
   result["CORE_BLOCKCHAIN_HARDFORK_VERSION"] = CORE_BLOCKCHAIN_HARDFORK_VERSION;
   result["CORE_BLOCKCHAIN_VERSION"] = CORE_BLOCKCHAIN_VERSION;
   result["CORE_BLOCK_INTERVAL"] = CORE_BLOCK_INTERVAL;
   result["CORE_BLOCKS_PER_DAY"] = CORE_BLOCKS_PER_DAY;
   result["CORE_BLOCKS_PER_HOUR"] = CORE_BLOCKS_PER_HOUR;
   result["CORE_BLOCKS_PER_YEAR"] = CORE_BLOCKS_PER_YEAR;
   result["CORE_CASHOUT_WINDOW_SECONDS"] = CORE_CASHOUT_WINDOW_SECONDS;
   result["CORE_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = CORE_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["CORE_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = CORE_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["CORE_CHAIN_ID"] = CORE_CHAIN_ID;
   result["CORE_COMMENT_REWARD_FUND_NAME"] = CORE_COMMENT_REWARD_FUND_NAME;
   result["CORE_CONTENT_APR_PERCENT"] = CORE_CONTENT_APR_PERCENT;
   result["CORE_CONTENT_CONSTANT_HF0"] = CORE_CONTENT_CONSTANT_HF0;
   result["CORE_CONTENT_REWARD_PERCENT"] = CORE_CONTENT_REWARD_PERCENT;
   result["CORE_CONVERSION_DELAY"] = CORE_CONVERSION_DELAY;
   result["CORE_CONVERSION_DELAY_PRE_HF_16"] = CORE_CONVERSION_DELAY_PRE_HF_16;
   result["CORE_CREATE_ACCOUNT_DELEGATION_RATIO"] = CORE_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["CORE_CREATE_ACCOUNT_DELEGATION_TIME"] = CORE_CREATE_ACCOUNT_DELEGATION_TIME;
   result["CORE_CREATE_ACCOUNT_WITH_STEEM_MODIFIER"] = CORE_CREATE_ACCOUNT_WITH_STEEM_MODIFIER;
   result["CORE_CURATE_APR_PERCENT"] = CORE_CURATE_APR_PERCENT;
   result["CORE_DEFAULT_SBD_INTEREST_RATE"] = CORE_DEFAULT_SBD_INTEREST_RATE;
   result["CORE_EQUIHASH_K"] = CORE_EQUIHASH_K;
   result["CORE_EQUIHASH_N"] = CORE_EQUIHASH_N;
   result["CORE_FEED_HISTORY_WINDOW"] = CORE_FEED_HISTORY_WINDOW;
   result["CORE_FEED_HISTORY_WINDOW_PRE_HF_16"] = CORE_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["CORE_FEED_INTERVAL_BLOCKS"] = CORE_FEED_INTERVAL_BLOCKS;
   result["CORE_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT"] = CORE_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT;
   result["CORE_GENESIS_TIME"] = CORE_GENESIS_TIME;
   result["CORE_HARDFORK_REQUIRED_WITNESSES"] = CORE_HARDFORK_REQUIRED_WITNESSES;
   result["CORE_INFLATION_NARROWING_PERIOD"] = CORE_INFLATION_NARROWING_PERIOD;
   result["CORE_INFLATION_RATE_START_PERCENT"] = CORE_INFLATION_RATE_START_PERCENT;
   result["CORE_INFLATION_RATE_STOP_PERCENT"] = CORE_INFLATION_RATE_STOP_PERCENT;
   result["CORE_INIT_MINER_NAME"] = CORE_INIT_MINER_NAME;
   result["CORE_INIT_PUBLIC_KEY_STR"] = CORE_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["CORE_INIT_PRIVATE_KEY"] = CORE_INIT_PRIVATE_KEY;
#endif
   result["CORE_INIT_SUPPLY"] = CORE_INIT_SUPPLY;
   result["CORE_INIT_TIME"] = CORE_INIT_TIME;
   result["CORE_IRREVERSIBLE_THRESHOLD"] = CORE_IRREVERSIBLE_THRESHOLD;
   result["CORE_LIQUIDITY_APR_PERCENT"] = CORE_LIQUIDITY_APR_PERCENT;
   result["CORE_LIQUIDITY_REWARD_BLOCKS"] = CORE_LIQUIDITY_REWARD_BLOCKS;
   result["CORE_LIQUIDITY_REWARD_PERIOD_SEC"] = CORE_LIQUIDITY_REWARD_PERIOD_SEC;
   result["CORE_LIQUIDITY_TIMEOUT_SEC"] = CORE_LIQUIDITY_TIMEOUT_SEC;
   result["CORE_MAX_ACCOUNT_NAME_LENGTH"] = CORE_MAX_ACCOUNT_NAME_LENGTH;
   result["CORE_MAX_ACCOUNT_WITNESS_VOTES"] = CORE_MAX_ACCOUNT_WITNESS_VOTES;
   result["CORE_MAX_ASSET_WHITELIST_AUTHORITIES"] = CORE_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["CORE_MAX_AUTHORITY_MEMBERSHIP"] = CORE_MAX_AUTHORITY_MEMBERSHIP;
   result["CORE_MAX_BLOCK_SIZE"] = CORE_MAX_BLOCK_SIZE;
   result["CORE_SOFT_MAX_BLOCK_SIZE"] = CORE_SOFT_MAX_BLOCK_SIZE;
   result["CORE_MAX_CASHOUT_WINDOW_SECONDS"] = CORE_MAX_CASHOUT_WINDOW_SECONDS;
   result["CORE_MAX_COMMENT_DEPTH"] = CORE_MAX_COMMENT_DEPTH;
   result["CORE_MAX_COMMENT_DEPTH_PRE_HF17"] = CORE_MAX_COMMENT_DEPTH_PRE_HF17;
   result["CORE_MAX_FEED_AGE_SECONDS"] = CORE_MAX_FEED_AGE_SECONDS;
   result["CORE_MAX_INSTANCE_ID"] = CORE_MAX_INSTANCE_ID;
   result["CORE_MAX_MEMO_SIZE"] = CORE_MAX_MEMO_SIZE;
   result["CORE_MAX_WITNESSES"] = CORE_MAX_WITNESSES;
   result["CORE_MAX_MINER_WITNESSES_HF0"] = CORE_MAX_MINER_WITNESSES_HF0;
   result["CORE_MAX_MINER_WITNESSES_HF17"] = CORE_MAX_MINER_WITNESSES_HF17;
   result["CORE_MAX_PERMLINK_LENGTH"] = CORE_MAX_PERMLINK_LENGTH;
   result["CORE_MAX_PROXY_RECURSION_DEPTH"] = CORE_MAX_PROXY_RECURSION_DEPTH;
   result["CORE_MAX_RATION_DECAY_RATE"] = CORE_MAX_RATION_DECAY_RATE;
   result["CORE_MAX_RESERVE_RATIO"] = CORE_MAX_RESERVE_RATIO;
   result["CORE_MAX_RUNNER_WITNESSES_HF0"] = CORE_MAX_RUNNER_WITNESSES_HF0;
   result["CORE_MAX_RUNNER_WITNESSES_HF17"] = CORE_MAX_RUNNER_WITNESSES_HF17;
   result["CORE_MAX_SHARE_SUPPLY"] = CORE_MAX_SHARE_SUPPLY;
   result["CORE_MAX_SIG_CHECK_DEPTH"] = CORE_MAX_SIG_CHECK_DEPTH;
   result["CORE_MAX_TIME_UNTIL_EXPIRATION"] = CORE_MAX_TIME_UNTIL_EXPIRATION;
   result["CORE_MAX_TRANSACTION_SIZE"] = CORE_MAX_TRANSACTION_SIZE;
   result["CORE_MAX_UNDO_HISTORY"] = CORE_MAX_UNDO_HISTORY;
   result["CORE_MAX_URL_LENGTH"] = CORE_MAX_URL_LENGTH;
   result["CORE_MAX_VOTE_CHANGES"] = CORE_MAX_VOTE_CHANGES;
   result["CORE_MAX_VOTED_WITNESSES_HF0"] = CORE_MAX_VOTED_WITNESSES_HF0;
   result["CORE_MAX_VOTED_WITNESSES_HF17"] = CORE_MAX_VOTED_WITNESSES_HF17;
   result["CORE_MAX_WITHDRAW_ROUTES"] = CORE_MAX_WITHDRAW_ROUTES;
   result["CORE_MAX_WITNESS_URL_LENGTH"] = CORE_MAX_WITNESS_URL_LENGTH;
   result["CORE_MIN_ACCOUNT_CREATION_FEE"] = CORE_MIN_ACCOUNT_CREATION_FEE;
   result["CORE_MIN_ACCOUNT_NAME_LENGTH"] = CORE_MIN_ACCOUNT_NAME_LENGTH;
   result["CORE_MIN_BLOCK_SIZE"] = CORE_MIN_BLOCK_SIZE;
   result["CORE_MIN_BLOCK_SIZE_LIMIT"] = CORE_MIN_BLOCK_SIZE_LIMIT;
   result["CORE_MIN_CONTENT_REWARD"] = CORE_MIN_CONTENT_REWARD;
   result["CORE_MIN_CURATE_REWARD"] = CORE_MIN_CURATE_REWARD;
   result["CORE_MIN_PERMLINK_LENGTH"] = CORE_MIN_PERMLINK_LENGTH;
   result["CORE_MIN_REPLY_INTERVAL"] = CORE_MIN_REPLY_INTERVAL;
   result["CORE_MIN_ROOT_COMMENT_INTERVAL"] = CORE_MIN_ROOT_COMMENT_INTERVAL;
   result["CORE_MIN_VOTE_INTERVAL_SEC"] = CORE_MIN_VOTE_INTERVAL_SEC;
   result["CORE_MINER_ACCOUNT"] = CORE_MINER_ACCOUNT;
   result["CORE_MINER_PAY_PERCENT"] = CORE_MINER_PAY_PERCENT;
   result["CORE_MIN_FEEDS"] = CORE_MIN_FEEDS;
   result["CORE_MINING_REWARD"] = CORE_MINING_REWARD;
   result["CORE_MINING_TIME"] = CORE_MINING_TIME;
   result["CORE_MIN_LIQUIDITY_REWARD"] = CORE_MIN_LIQUIDITY_REWARD;
   result["CORE_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = CORE_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["CORE_MIN_PAYOUT_SBD"] = CORE_MIN_PAYOUT_SBD;
   result["CORE_MIN_POW_REWARD"] = CORE_MIN_POW_REWARD;
   result["CORE_MIN_PRODUCER_REWARD"] = CORE_MIN_PRODUCER_REWARD;
   result["CORE_MIN_RATION"] = CORE_MIN_RATION;
   result["CORE_MIN_TRANSACTION_EXPIRATION_LIMIT"] = CORE_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["CORE_MIN_TRANSACTION_SIZE_LIMIT"] = CORE_MIN_TRANSACTION_SIZE_LIMIT;
   result["CORE_MIN_UNDO_HISTORY"] = CORE_MIN_UNDO_HISTORY;
   result["CORE_NULL_ACCOUNT"] = CORE_NULL_ACCOUNT;
   result["CORE_NUM_INIT_MINERS"] = CORE_NUM_INIT_MINERS;
   result["CORE_ORIGINAL_MIN_ACCOUNT_CREATION_FEE"] = CORE_ORIGINAL_MIN_ACCOUNT_CREATION_FEE;
   result["CORE_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = CORE_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["CORE_OWNER_AUTH_RECOVERY_PERIOD"] = CORE_OWNER_AUTH_RECOVERY_PERIOD;
   result["CORE_OWNER_CHALLENGE_COOLDOWN"] = CORE_OWNER_CHALLENGE_COOLDOWN;
   result["CORE_OWNER_CHALLENGE_FEE"] = CORE_OWNER_CHALLENGE_FEE;
   result["CORE_OWNER_UPDATE_LIMIT"] = CORE_OWNER_UPDATE_LIMIT;
   result["CORE_POST_AVERAGE_WINDOW"] = CORE_POST_AVERAGE_WINDOW;
   result["CORE_POST_MAX_BANDWIDTH"] = CORE_POST_MAX_BANDWIDTH;
   result["CORE_POST_REWARD_FUND_NAME"] = CORE_POST_REWARD_FUND_NAME;
   result["CORE_POST_WEIGHT_CONSTANT"] = CORE_POST_WEIGHT_CONSTANT;
   result["CORE_POW_APR_PERCENT"] = CORE_POW_APR_PERCENT;
   result["CORE_PRODUCER_APR_PERCENT"] = CORE_PRODUCER_APR_PERCENT;
   result["CORE_PROXY_TO_SELF_ACCOUNT"] = CORE_PROXY_TO_SELF_ACCOUNT;
   result["CORE_SBD_INTEREST_COMPOUND_INTERVAL_SEC"] = CORE_SBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["CORE_SECONDS_PER_YEAR"] = CORE_SECONDS_PER_YEAR;
   result["CORE_RECENT_RSHARES_DECAY_RATE_HF19"] = CORE_RECENT_RSHARES_DECAY_RATE_HF19;
   result["CORE_RECENT_RSHARES_DECAY_RATE_HF17"] = CORE_RECENT_RSHARES_DECAY_RATE_HF17;
   result["CORE_REVERSE_AUCTION_WINDOW_SECONDS"] = CORE_REVERSE_AUCTION_WINDOW_SECONDS;
   result["CORE_ROOT_POST_PARENT"] = CORE_ROOT_POST_PARENT;
   result["CORE_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = CORE_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["CORE_SAVINGS_WITHDRAW_TIME"] = CORE_SAVINGS_WITHDRAW_TIME;
   result["CORE_SBD_START_PERCENT"] = CORE_SBD_START_PERCENT;
   result["CORE_SBD_STOP_PERCENT"] = CORE_SBD_STOP_PERCENT;
   result["CORE_SECOND_CASHOUT_WINDOW"] = CORE_SECOND_CASHOUT_WINDOW;
   result["CORE_SOFT_MAX_COMMENT_DEPTH"] = CORE_SOFT_MAX_COMMENT_DEPTH;
   result["CORE_START_MINER_VOTING_BLOCK"] = CORE_START_MINER_VOTING_BLOCK;
   result["CORE_START_VESTING_BLOCK"] = CORE_START_VESTING_BLOCK;
   result["CORE_SYMBOL"] = CORE_SYMBOL;
   result["CORE_TEMP_ACCOUNT"] = CORE_TEMP_ACCOUNT;
   result["CORE_UPVOTE_LOCKOUT_HF7"] = CORE_UPVOTE_LOCKOUT_HF7;
   result["CORE_UPVOTE_LOCKOUT_HF17"] = CORE_UPVOTE_LOCKOUT_HF17;
   result["CORE_VESTING_FUND_PERCENT"] = CORE_VESTING_FUND_PERCENT;
   result["CORE_VESTING_WITHDRAW_INTERVALS"] = CORE_VESTING_WITHDRAW_INTERVALS;
   result["CORE_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = CORE_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["CORE_VESTING_WITHDRAW_INTERVAL_SECONDS"] = CORE_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["CORE_VOTE_CHANGE_LOCKOUT_PERIOD"] = CORE_VOTE_CHANGE_LOCKOUT_PERIOD;
   result["CORE_VOTE_DUST_THRESHOLD"] = CORE_VOTE_DUST_THRESHOLD;
   result["CORE_VOTE_REGENERATION_SECONDS"] = CORE_VOTE_REGENERATION_SECONDS;
   result["STEEM_SYMBOL"] = STEEM_SYMBOL;
   result["STMD_SYMBOL"] = STMD_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VIRTUAL_SCHEDULE_LAP_LENGTH2;

   return result;
}

} } // core::protocol
